export type Role = 'admin' | 'manager' | 'user' | 'viewer' | 'comercial' | 'producao' | 'compras' | 'estoque' | 'financeiro'
export type Module = 'usuarios' | 'orcamentos' | 'produtos' | 'clientes' | 'categorias' | 'materiais' | 'sistema' | 'configuracoes' | 'sequencias' | 'auditoria' | 'dashboard' | 'fornecedores' | 'requisicoes' | 'producao' | 'estoque' | 'relatorios'
export type Action = 'create' | 'read' | 'update' | 'delete' | 'manage' | 'export'
import { ForbiddenException } from '@/app/exceptions'

const PERMISSIONS: Record<Role, Record<Module, Action[]>> = {
  admin: {
    usuarios: ['create', 'read', 'update', 'delete', 'manage'],
    orcamentos: ['create', 'read', 'update', 'delete', 'manage', 'export'],
    produtos: ['create', 'read', 'update', 'delete', 'manage'],
    clientes: ['create', 'read', 'update', 'delete', 'manage'],
    categorias: ['create', 'read', 'update', 'delete', 'manage'],
    materiais: ['create', 'read', 'update', 'delete', 'manage'],
    sistema: ['read', 'update', 'manage'],
    configuracoes: ['read', 'update', 'manage'],
    sequencias: ['read', 'update', 'manage'],
    auditoria: ['read', 'manage'],
    dashboard: ['read'],
    fornecedores: ['create', 'read', 'update', 'delete', 'manage'],
    requisicoes: ['create', 'read', 'update', 'delete', 'manage', 'export'],
    producao: ['create', 'read', 'update', 'delete', 'manage', 'export'],
    estoque: ['create', 'read', 'update', 'delete', 'manage', 'export'],
    relatorios: ['create', 'read', 'update', 'delete', 'manage', 'export'],
  },
  manager: {
    usuarios: ['read'],
    orcamentos: ['create', 'read', 'update', 'delete', 'export'],
    produtos: ['create', 'read', 'update', 'delete'],
    clientes: ['create', 'read', 'update', 'delete'],
    categorias: ['create', 'read', 'update'],
    materiais: ['create', 'read', 'update'],
    sistema: ['read'],
    configuracoes: ['read'],
    sequencias: ['read'],
    auditoria: [],
    dashboard: ['read'],
    fornecedores: ['create', 'read', 'update', 'delete'],
    requisicoes: ['create', 'read', 'update', 'delete', 'export'],
    producao: ['create', 'read', 'update', 'delete', 'export'],
    estoque: ['create', 'read', 'update', 'delete', 'export'],
    relatorios: ['create', 'read', 'update', 'export'],
  },
  user: {
    usuarios: ['read'],
    orcamentos: ['create', 'read', 'update'],
    produtos: ['read'],
    clientes: ['read'],
    categorias: ['read'],
    materiais: ['read'],
    sistema: [],
    configuracoes: [],
    sequencias: [],
    auditoria: [],
    dashboard: ['read'],
    fornecedores: ['read'],
    requisicoes: ['create', 'read', 'update'],
    producao: ['read'],
    estoque: ['read'],
    relatorios: ['read'],
  },
  viewer: {
    usuarios: [],
    orcamentos: ['read'],
    produtos: ['read'],
    clientes: ['read'],
    categorias: ['read'],
    materiais: ['read'],
    sistema: [],
    configuracoes: [],
    sequencias: [],
    auditoria: [],
    dashboard: ['read'],
    fornecedores: ['read'],
    requisicoes: ['read'],
    producao: ['read'],
    estoque: ['read'],
    relatorios: ['read'],
  },
  comercial: {
    usuarios: [],
    orcamentos: ['create', 'read', 'update', 'delete', 'export'],
    produtos: ['read'],
    clientes: ['create', 'read', 'update', 'delete'],
    categorias: ['read'],
    materiais: ['read'],
    sistema: [],
    configuracoes: [],
    sequencias: [],
    auditoria: [],
    dashboard: ['read'],
    fornecedores: [],
    requisicoes: [],
    producao: ['read'],
    estoque: ['read'],
    relatorios: ['read', 'export'],
  },
  producao: {
    usuarios: [],
    orcamentos: ['read'],
    produtos: ['read'],
    clientes: ['read'],
    categorias: ['read'],
    materiais: ['read'],
    sistema: [],
    configuracoes: [],
    sequencias: [],
    auditoria: [],
    dashboard: ['read'],
    fornecedores: ['read'],
    requisicoes: ['create', 'read', 'update'],
    producao: ['create', 'read', 'update', 'delete', 'export'],
    estoque: ['read'],
    relatorios: ['read'],
  },
  compras: {
    usuarios: [],
    orcamentos: ['read'],
    produtos: ['read'],
    clientes: ['read'],
    categorias: ['read'],
    materiais: ['create', 'read', 'update'],
    sistema: [],
    configuracoes: [],
    sequencias: [],
    auditoria: [],
    dashboard: ['read'],
    fornecedores: ['create', 'read', 'update', 'delete', 'manage'],
    requisicoes: ['create', 'read', 'update', 'delete', 'manage', 'export'],
    producao: ['read'],
    estoque: ['read'],
    relatorios: ['read', 'export'],
  },
  estoque: {
    usuarios: [],
    orcamentos: [],
    produtos: ['read'],
    clientes: [],
    categorias: ['read'],
    materiais: ['create', 'read', 'update'],
    sistema: [],
    configuracoes: [],
    sequencias: [],
    auditoria: [],
    dashboard: ['read'],
    fornecedores: ['read'],
    requisicoes: ['read', 'update'],
    producao: ['read'],
    estoque: ['create', 'read', 'update', 'manage', 'export'],
    relatorios: ['read', 'export'],
  },
  financeiro: {
    usuarios: [],
    orcamentos: ['read', 'export'],
    produtos: ['read'],
    clientes: ['read'],
    categorias: [],
    materiais: ['read'],
    sistema: [],
    configuracoes: [],
    sequencias: [],
    auditoria: [],
    dashboard: ['read'],
    fornecedores: ['read'],
    requisicoes: ['read'],
    producao: ['read'],
    estoque: ['read'],
    relatorios: ['create', 'read', 'update', 'delete', 'manage', 'export'],
  },
}

export function hasPermission(role: string, module: Module, action: Action): boolean {
  const rolePerms = PERMISSIONS[role as Role]
  if (!rolePerms) return false
  const modulePerms = rolePerms[module]
  if (!modulePerms) return false
  return modulePerms.includes(action) || modulePerms.includes('manage')
}

export function requirePermission(role: string, module: Module, action: Action): void {
  if (!hasPermission(role, module, action)) {
    throw new ForbiddenException('Você não tem permissão para realizar esta ação')
  }
}